# Generated by Django 5.0.4 on 2024-04-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assesments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_questions', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('is_public', models.BooleanField()),
                ('section_type', models.CharField(choices=[('READING', 'Reading'), ('LISTENING', 'Listening'), ('WRITING', 'Writing'), ('SPEAKING', 'Speaking')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='assesment_images/')),
                ('book_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
