# Generated by Django 5.0.4 on 2024-06-01 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_alter_userpackage_exams_taken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('json_file', models.FileField(upload_to='json_data/')),
            ],
        ),
    ]
