# Generated by Django 5.0.4 on 2024-04-09 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0002_question_part_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('type', models.CharField(choices=[('PASSAGE_SIMPLE', 'Simple Passage'), ('PASSAGE_MULTI_HEADING', 'Multi heading Passages')], max_length=50)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Passage', to='mocktest.part', verbose_name='Part')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.CharField(default='', max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('start_question_num', models.IntegerField(verbose_name='Start Question Number')),
                ('end_question_num', models.IntegerField(verbose_name='End Question Number')),
                ('question_type', models.CharField(max_length=50, verbose_name=[('MULTIPLE_CHOICE_ONE_ANSWER', 'Multiple Choice Question'), ('MULTIPLE_CHOICE_MORE_ANSWER', 'Multiple Choice More Answers'), ('IDENTIFYING_INFORMATION', 'Identifying Information'), ('COMPLETION', 'Completion'), ('TABLE_COMPLETION', 'Table Completion'), ('MATCHING', 'Matching'), ('MATCHING_HEADINGS', 'Matching Headings')])),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionGroups', to='mocktest.part', verbose_name='Part')),
            ],
            options={
                'verbose_name': 'Question Group',
                'verbose_name_plural': 'Question Groups',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mocktest.questiongroup'),
            preserve_default=False,
        ),
    ]
