# Generated by Django 5.0.4 on 2024-06-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('mocktest', '0003_mocktest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
    ]
