# Generated by Django 5.0.4 on 2024-06-02 21:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_id'),
        ('mocktest', '0003_mocktest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('answers', models.FileField(upload_to='json_data/correct_answers/')),
                ('mocktest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest')),
            ],
        ),
        migrations.CreateModel(
            name='UserMockTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reading_answers', models.FileField(blank=True, null=True, upload_to='json_data/reading_answers/')),
                ('listening_answers', models.FileField(blank=True, null=True, upload_to='json_data/listening_answers/')),
                ('writing_answers', models.FileField(blank=True, null=True, upload_to='json_data/writing_answers/')),
                ('feedback', models.FileField(blank=True, null=True, upload_to='json_data/ai_feedback/')),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PASSED', 'passed'), ('LISTENING', 'listening'), ('READING', 'reading')], max_length=15)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('FREE', 'free'), ('PAID', 'paid')], max_length=15)),
                ('mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.mocktest')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answers', models.FileField(upload_to='json_data/user_answers/')),
                ('type', models.CharField(choices=[('WITH_FEEDBACK', 'with_feedback'), ('WITHOUT_FEEDBACK', 'without_feedback')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.usermocktest')),
            ],
        ),
    ]
