# Generated by Django 5.0.4 on 2024-06-09 07:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_username'),
        ('mocktest', '0004_correctanswers_usermocktest_usertestresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='userpackage',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='usertestresult',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mocktests_included', models.ManyToManyField(related_name='packages', to='mocktest.mocktest')),
            ],
        ),
        migrations.CreateModel(
            name='UserPackagePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remaining_mocktests', models.PositiveIntegerField()),
                ('package_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocktest.packageplan')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='UserPackage',
        ),
    ]
