# Generated by Django 5.0.4 on 2024-06-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0005_remove_userpackage_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplan',
            name='num_mock_tests',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
