# Generated by Django 5.0.4 on 2024-06-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0008_mocktest_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mocktest',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='usermocktest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='usermocktest',
            name='title',
        ),
    ]
