# Generated by Django 5.0.4 on 2024-06-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0009_rename_name_mocktest_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctanswers',
            name='answers',
        ),
        migrations.AddField(
            model_name='correctanswers',
            name='listening_answers',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctanswers',
            name='reading_answers',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_answers', models.JSONField()),
                ('reading_answers', models.JSONField()),
                ('listening_correct_answers', models.JSONField()),
                ('reading_correct_answers', models.JSONField()),
                ('listening_results', models.JSONField()),
                ('reading_results', models.JSONField()),
                ('listening_score', models.IntegerField()),
                ('reading_score', models.IntegerField()),
                ('user_mocktest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='mocktest.usermocktest')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTestResult',
        ),
    ]
