# Generated by Django 5.0.4 on 2024-06-12 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0011_useranswer_listening_band_useranswer_reading_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='passed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
