# Generated by Django 5.0.4 on 2024-06-12 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0012_useranswer_passed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='writing_answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='writing_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='writing_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='passed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 13, 44, 26, 614945, tzinfo=datetime.timezone.utc)),
        ),
    ]
