# Generated by Django 5.0.4 on 2024-06-12 13:58

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0013_useranswer_writing_answers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='listening_band',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='passed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 13, 58, 55, 622100, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='reading_band',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='writing_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='WritingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_writing_answer', models.JSONField()),
                ('ai_feedback', models.JSONField()),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_feedback_user', to='mocktest.useranswer')),
            ],
        ),
    ]
