# Generated by Django 5.0.4 on 2024-06-12 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0014_alter_useranswer_listening_band_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='passed_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 12, 18, 32, 28, 518149, tzinfo=datetime.timezone.utc)),
        ),
    ]
