# Generated by Django 5.0.4 on 2024-06-12 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocktest', '0015_alter_useranswer_passed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='passed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
